In [45]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

In [30]:
df = pd.read_excel("Distro_Detail_v1.xlsx")

In [31]:
df2 = df[df['Account'].str.contains("Investor ")]

In [32]:
df_rep = pd.read_excel("Rep_Lookup.xlsx", header = None, names = ['A','B','C'])

In [33]:
df_rep = df_rep.drop(['A'], axis=1)

In [34]:
df2 = df2.merge(df_rep, how='left', left_on = 'Account', right_on = 'B')

In [ ]:
df2['Month'] = df2['Distribution date'].dt.month
df2['Quarter'] = df2['Distribution date'].dt.quarter

In [38]:
df_pivot = pd.pivot_table(df2,index=["C"], values=["Gross distributions"], 
columns = ["Quarter","Month"], aggfunc=[np.sum],fill_value=0,margins=True)

In [39]:
df_pivot

                        sum                                                    \
        Gross distributions
Quarter                   1                                    2
Month                     1            2           3           4            5
C
Ajey              108666.89    365390.40    55302.60   358033.59   2204925.55
Bill              201861.74    322612.39    88905.53   354158.60   2041643.77
Carlos            127196.69    746283.35    95440.77   383765.10   2224303.92
Dan               104787.62    405617.76    36423.28   255289.08   1228228.31
Doug              104868.55    323983.75    70577.01   236046.70   1377183.71
House             126624.71    369058.34    85721.50   309789.39   1859957.90
Jay                94103.63   1028223.86    89285.15   418564.53   1550182.58
John              100455.24    977784.39    79053.28   338673.53   1395500.13
Justin             66677.06    661421.17    46454.99   331960.10    994845.42
Luke              138059.74   1090732.62    64559.97   254251.76   1348082.43
MAGIC             112039.80    454339.48    79736.78   407816.31   2834845.79
Manoj              81796.70    636944.49    46460.01   287235.87   1283589.13
Pat               190645.10   1620446.34   146382.30   692529.17   2818988.70
Sage              130978.45    840832.78    52169.02   544149.36   1156384.82
Sandeep           114330.43   1287930.15   131855.06   540155.52   2463335.13
Sanjay             94500.51    569036.56    51315.36   255842.98   1210256.56
Simon             100362.71    769457.11    70257.22   229584.40   1378629.33
Suraj              66886.42    247737.95    25185.41   175423.31    932194.02
Trent             103997.34    415236.13    61083.51   267063.08   1673954.01
All              2168839.33  13133069.02  1376168.75  6640332.38  31977031.21

                                                                     \

Quarter                        3                                  4
Month             6            7           8           9         12
C
Ajey       80853.17    594136.98   120846.19    78624.88     841.70
Bill      108004.00    442786.78   196669.32    70280.16    3310.51
Carlos     94412.37    482956.27   177749.95    77049.87   15285.63
Dan        74702.04    308605.81    45364.37    18274.07    1714.15
Doug       65897.86    664966.34   278817.83   157569.34   15154.14
House      89102.49    571776.08   255724.18   159075.65    1324.20
Jay       107793.81    427109.29   136877.63    55647.73   20463.06
John       95765.58    353463.08   263208.82   135428.20    3310.51
Justin     67313.62    420065.13    97369.33    49010.86       0.00
Luke      111211.63    522528.16   488168.54   291251.15   12079.10
MAGIC      69351.67    474479.40    85922.28    27928.02    1052.05
Manoj      81926.16    402848.50   219580.12   118418.64    4362.56
Pat       165851.10   1072016.84   571669.08   296451.42    8984.32
Sage       80998.54    516467.07    98048.05    15655.72    3162.10
Sandeep   155052.89   1449945.32   544076.56   281382.59   18934.04
Sanjay     55939.07    543119.18   132919.02    42970.77    1052.05
Simon      69624.01    636703.19   262491.91   138967.41    8570.22
Suraj      45283.28    421355.46   211647.02    99868.56    3310.51
Trent      50307.51    705285.42   270599.51   171040.54    7362.56
All      1669390.80  11010614.30  4457749.71  2284895.58  130273.41



Quarter          All
Month
C
Ajey      3967621.95
Bill      3830232.80
Carlos    4424443.92
Dan       2479006.49
Doug      3295065.23
House     3828154.44
Jay       3928251.27
John      3742642.76
Justin    2735117.68
Luke      4320925.10
MAGIC     4547511.58
Manoj     3163162.18
Pat       7583964.37
Sage      3438845.91
Sandeep   6986997.69
Sanjay    2956952.06
Simon     3664647.51
Suraj     2228891.94
Trent     3725929.61
All      74848364.49

In [ ]:
plt.figure(figsize=(20,6))
sns.swarmplot(x='C', 
              y='Gross distributions', 
              data=df2, 
              hue='Quarter', 
              split=True)